version: "3.8"
services:
  app:
    build: .
    container_name: pm-api
    volumes:
      - ./src:/pm-api/src # Live code reload
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    command: npm run dev # Use nodemon in development
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: pm-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:  # Add healthcheck configuration
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pg-data: